import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import coursesRouter from "./courses";
import lessonsRouter from "./lessons";
import enrollmentsRouter from "./enrollments";
import liveClassesRouter from "./live-classes";
import attendanceRouter from "./attendance";
import communityRouter from "./community";
import channelsRouter from "./channels";
import tradingRouter from "./trading";
import dashboardRouter from "./dashboard";
import assessmentsRouter from "./assessments";
import engagementRouter from "./engagement";
import gatesRouter from "./gates";
import sectionsRouter from "./sections";
import marketRouter from "./market";
import uploadRouter from "./upload";
import instructorRouter from "./instructor";
import adminRouter from "./admin";
import notificationsRouter from "./notifications";
import batchesRouter from "./batches";
import setupRouter from "./setup";
import resourcesRouter from "./resources";
import discussionsRouter from "./discussions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(coursesRouter);
router.use(lessonsRouter);
router.use(enrollmentsRouter);
router.use(liveClassesRouter);
router.use(attendanceRouter);
router.use(communityRouter);
router.use(channelsRouter);
router.use(tradingRouter);
router.use(dashboardRouter);
router.use(assessmentsRouter);
router.use(engagementRouter);
router.use(gatesRouter);
router.use(sectionsRouter);
router.use(marketRouter);
router.use(uploadRouter);
router.use(instructorRouter);
router.use(adminRouter);
router.use(notificationsRouter);
router.use(batchesRouter);
router.use(setupRouter);
router.use(resourcesRouter);
router.use(discussionsRouter);

export default router;
